#!/bin/bash

JOB_NAME=route53_backup

RUN_DIR=/var/vcap/sys/run/$JOB_NAME
LOG_DIR=/var/vcap/sys/log/$JOB_NAME
PIDFILE=$RUN_DIR/$JOB_NAME.pid

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    # Add backup.cron cron line as last entry in crontab
    (crontab -l | sed /$JOB_NAME/d; cat /var/vcap/jobs/$JOB_NAME/config/backup.cron) | sed /^$/d | crontab

    # Tell monit that everything is ok for a long time
    echo 1 >> $PIDFILE

    ;;

  stop)
    crontab -l | sed /$JOB_NAME/d | sed /^$/d | crontab

    rm -f $PIDFILE

    ;;

  *)
  echo "Usage: ctl {start|stop}" ;;
esac
